### ISSUE TITLE
How to save the segmented word to file?

### ISSUE THREAD

**Issue by yapingzhao** [aalto-speech/morfessor#11]
Hi,
I use the following command for model training（morfessor2.0)：
morfessor-train --traindata-list --logfile=log.log -S model.segm -d ones inputdata.txt 
Then use the following command for word segmentation：
 morfessor-segment -L model.segm test.txt 
Why is the output in the terminal after the word segmentation? How to save the segmented word to Specified file?

Looking forward to your advice or answers.
Best regards,

yapingzhao

**Comment by psmit** [comment]
You can either use a shell redirect or use the option `-o filename`
