### ISSUE TITLE
Segmented output format

### ISSUE THREAD

**Issue by valentinmace** [aalto-speech/morfessor#16]
I used `morfessor-segment -L en.model test.data  > test.morf`

It works, however the text in my resulting file `test.morf` has a word on each line. As I am using corpus with **one sentence on each line** I would like to have to same output format but I cannot find how to achieve that

Thanks in advance

**Comment by valentinmace** [comment]
**Answer:**

`morfessor-segment -L en.model -o test.morf --output-format '{analysis} ' test.data --output-newlines`

Maybe you want to add a --output-format-separator '@@ ' to cleary define where words are segmented

**Comment by svirpioj** [comment]
Yes, the output format options are documented at https://morfessor.readthedocs.io/en/latest/cmdtools.html#data-format-command-line-options, but not so clearly. Thanks for providing the answer, too!
