### ISSUE TITLE
How do I control dictionary size

### ISSUE THREAD

**Issue by HanelYuki** [aalto-speech/morfessor#18]

**Comment by svirpioj** [comment]
See https://morfessor.readthedocs.io/en/latest/cmdtools.html#corpusweight-alpha-tuning

The size of the output lexicon can be controlled by the alpha or `corpusweight` hyperparameter:
```
  -w <float>, --corpusweight <float>
                        corpus weight parameter (default 1.0); sets the
                        initial value if other tuning options are used
```
Increase the value above one to get larger lexicon, and decrease close to zero for a smaller one.

There's also `--num-morph-types` option to set the desired size, and the algorithm tries to get it approximately, but in some situations it may not work very well.

(Sorry for the delay in answering.)
