### ISSUE TITLE
Trained models

### ISSUE THREAD

**Issue by gartenfeld** [aalto-speech/morfessor#3]
Is there a trained model for Finnish available for download somewhere?

**Comment by shadowrock** [comment]
Hi David!

I don't know if there is a trained model available at the moment. A Finnish wordlist with frequencies may be downloaded from the Morpho Challenge pages:
http://research.ics.aalto.fi/events/morphochallenge2010/datasets.shtml#download
http://research.ics.aalto.fi/events/morphochallenge2010/data/wordlist-2010.fin

http://morfessor.readthedocs.org has some instructions on training the model.

Best,
Matti

**Comment by gartenfeld** [comment]
Many thanks. I've just tried models using the Parole frequency lists, with results comparable to the unsupervised demo shown in some papers.
